version: "3"

services:
  git:
    build: .
    volumes:
      - ./git/public/:/srv/git/
      - ./cgitrc:/etc/cgitrc
      - ./cgit/:/usr/share/cgit/
      - ./cgit/favicon-public.svg:/usr/share/cgit/favicon.svg
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    restart: on-failure

  gitp:
    build: .
    volumes:
      - ./git/private/:/srv/git/
      - ./cgitrc:/etc/cgitrc
      - ./cgit/:/usr/share/cgit/
      - ./cgit/favicon-private.svg:/usr/share/cgit/favicon.svg
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80
    restart: on-failure
