version: "3"

services:
  git:
    build: ./cgit
    volumes:
      - ./git/public/:/srv/git/
      - ./cgit/cgitrc:/etc/cgitrc
      - ./cgit/style.css:/usr/share/cgit/style.css
      - ./cgit/head.html:/usr/share/cgit/head.html
      - ./cgit/favicon-public.svg:/usr/share/cgit/favicon.svg
      - ./cgit/nginx.public.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    restart: on-failure

  gitp:
    build:
      context: ./cgit
      args:
        GITHUB_USER: "${GITHUB_USER?err}"
        BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD?err}"
    volumes:
      - ./git/private/:/srv/git/
      - ./cgit/cgitrc:/etc/cgitrc
      - ./cgit/style.css:/usr/share/cgit/style.css
      - ./cgit/head.html:/usr/share/cgit/head.html
      - ./cgit/favicon-private.svg:/usr/share/cgit/favicon.svg
      - ./cgit/nginx.private.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80
    restart: on-failure

  sync:
    build: ./sync
    volumes:
      - ./git/:/srv/git/
    environment:
      GITHUB_USER: "${GITHUB_USER?err}"
      GITHUB_TOKEN: "${GITHUB_TOKEN?err}"
      REPOS_PATH: /srv/git
    restart: on-failure
