version: "3"

services:
  git:
    build: ./cgit
    volumes:
      - ./git/public/:/srv/git/
      - ./cgit/cgitrc:/etc/cgitrc
      - ./cgit/style.css:/usr/share/cgit/style.css
      - ./cgit/head.html:/usr/share/cgit/head.html
      - ./cgit/favicon-public.svg:/usr/share/cgit/favicon.svg
      - ./cgit/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    restart: on-failure

  gitp:
    build: ./cgit
    volumes:
      - ./git/private/:/srv/git/
      - ./cgit/cgitrc:/etc/cgitrc
      - ./cgit/style.css:/usr/share/cgit/style.css
      - ./cgit/head.html:/usr/share/cgit/head.html
      - ./cgit/favicon-private.svg:/usr/share/cgit/favicon.svg
      - ./cgit/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80
    restart: on-failure
